### ISSUE TITLE
Handle transport disconnects

### ISSUE THREAD

**Issue by pcppcp** [raiden-network/raiden-monitoring-service#3]
If Matrix server goes down, client should reconnect and MS must still react on blockchain events.

**Comment by karlb** [comment]
Looking at https://github.com/raiden-network/raiden-libs/blob/master/raiden_libs/transport/matrix.py#L81-L101, this is already the case. We're catching `requests.exceptions.ConnectionError` and reconnect. There's no test for it, yet. But if we want to add one, it would make more sense to put it into raiden-libs, since the code that should be tested lives there.

**Comment by karlb** [comment]
@palango: reopen if you think there's still a todo left.

**Comment by palango** [comment]
I thought more about the web3 client that the matrix client and the same middleware solution you did for the PFS.
